### ISSUE TITLE
Contrib project has a maven dependency with an older version of guava library. 

### ISSUE THREAD

**Issue by BitBaron** [internetarchive/heritrix3#311]
Changes introduced in https://github.com/internetarchive/heritrix3/pull/304 broke the contrib project.

The `org.archive.modules.recrawl.hbase` package has a resolved dependency on version 12 of guava and other versions of the hbase client I've sampled in the POM resolve to guava v12 or lower.

```xml
<dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-client</artifactId>
        <version>0.98.6-cdh5.3.5</version>
        <exclusions>
                <exclusion>
                        <artifactId>jets3t</artifactId>
                        <groupId>net.java.dev.jets3t</groupId>
                </exclusion>
                <exclusion>
                        <artifactId>junit</artifactId>
                        <groupId>junit</groupId>
                </exclusion>
                <!-- tools.jar is not available in JDK 11 so exclude it
                     hbase-client accidentally leaked it as a transitive dependency
                     https://issues.apache.org/jira/browse/HBASE-13963 --> 
                <exclusion>
                        <groupId>jdk.tools</groupId>
                        <artifactId>jdk.tools</artifactId>
                </exclusion>
        </exclusions>
</dependency>
```

I also realize there are no tests for this so it didn't show up in CI or anywhere else.

**Comment by ato** [comment]
Ah! I was seeing this as a ClassNotFoundException for com.google.common.io.BaseEncoding in another project that depends on heritrix and was wondering what was going on. I think excluding hbase-client's older version of Guava should fix it?

Or does hbase-client actually relies on something in 12 that was removed in 17? Unfortunately I don't have a proper way to test it. I created an instance of org.archive.modules.recrawl.hbase.HBase and called start() and got errors about connecting to Zookeeper rather than class loading issues which seems promising at least.

**Comment by BitBaron** [comment]
I'm not sure. We are looking into removing Hbase support all together and further simplifying.

**Comment by hennekey** [comment]
I can probably work on this to resolve the dependency issues. Guava 12 or (17 for that matter) are rather out of date.

**Comment by csrster** [comment]
We think this may have resulted in our harvest jobs stopping sending Cookies entirely.

**Comment by anjackson** [comment]
That's odd @csrster - Looking at our recent crawls (on 3.4.0-20200518) I can see cookies in the requests. They are still broken by #259 but otherwise appear fine.  Do you have any more details?

**Comment by csrster** [comment]
I mean the original bug may have broken our Cookies, not the fix. I thought it worth mentioning in case anybody else needs to look through their old harvests to check for problems they didn't notice at the time. We noticed the bug in NetarchiveSuite in Nov '19 but it took quite a lot of detective work to track the cause down to guava 12 - see https://sbforge.org/jira/browse/NAS-2861
